
import java.awt.Color;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author G-FIRE
 */
public class Telafunci extends javax.swing.JFrame {

    /**
     * Creates new form TelaAdm
     */
    public Telafunci() {
        initComponents();
        //Ocultando os paineis ao iniciar a aplicação pela primeira vez (exceto o de inicio)
        pacPan.setVisible(false);
    }

    private void obtemPacientes() {
        //Definindo modelo de pessoasTable para DefaultTableModel
        DefaultTableModel modelo = (DefaultTableModel) pessoasTable.getModel();
        //Definindo numero de filas por padrão para 0:
        modelo.setNumRows(0);
        PacienteDAO pDAO = new PacienteDAO();

        try {
            //Laço de repetição para peencher as filas da tabela
            for (Paciente p : pDAO.obtemFila()) {
                //Adicionando nova fila
                modelo.addRow(new Object[]{
                    //com os valores obtidos:
                    p.getCodigo(),
                    p.getNome(),
                    p.getIdade(),
                    p.getEndereco(),
                    p.getUf(),
                    p.getAreaSaude(),
                    p.getPrioridade(),
                    p.getDataVacina()
                });
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro técnico, Tente novamente mais tarde");
            }
        
    }
    /**
     * Método para mudar cor do botão do menu.
     *
     * @param pane O painel colocado no parâmetro deve ser o painel
     * correspondente ao botão selecionado pelo usuário
     * <br>Exemplo: se o usuário selecionar a opção Pacientes o método muda a
     * cor do botão para o usuário identificar qual opção foi selecionada.
     */
    public void mudarCor(JPanel pane) {
        pane.setBackground(new Color(130, 145, 143));
    }

    /**
     * Método para mudar o painel exibido na tela do usuário
     * <br>O primeiro parâmetro define o painel que sera exibido
     * <br>Os demais parâmetros ocultam os demais paineis
     */
    public void mudarPanel(JPanel panel, JPanel pane2) {
        panel.setVisible(true);
        pane2.setVisible(false);
    }

    /**
     * Método para voltar cor dos demais paineis que não foram selecionado
     * <br>Exemplo: caso o usuário seleciona o botão de pacientes o método deve
     * ser usado para voltar a cor dos 4 paineis restantes
     * <br>Destancando assim o painel com o método "mudarCor".
     */
    public void voltarCor(JPanel pane) {
        pane.setBackground(new Color(73, 149, 136));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        inicioBtn = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pacienteBtn = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        paineis = new javax.swing.JLayeredPane();
        inicioPan = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        pacPan = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        confirmarVacinaBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pessoasTable = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        sairMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Salvation Line");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Imagens/medical_doctor_24px.png")).getImage());
        setLocationByPlatform(true);
        setResizable(false);

        background.setBackground(new java.awt.Color(196, 231, 219));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu.setBackground(new java.awt.Color(73, 138, 136));
        menu.setForeground(new java.awt.Color(105, 221, 243));

        inicioBtn.setBackground(new java.awt.Color(130, 145, 143));
        inicioBtn.setForeground(new java.awt.Color(73, 149, 136));
        inicioBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inicioBtnMouseClicked(evt);
            }
        });
        inicioBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/home.png"))); // NOI18N
        inicioBtn.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Inicio");
        inicioBtn.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, -1, 66));

        pacienteBtn.setBackground(new java.awt.Color(73, 149, 136));
        pacienteBtn.setForeground(new java.awt.Color(73, 149, 136));
        pacienteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pacienteBtnMouseClicked(evt);
            }
        });
        pacienteBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/vacina.png"))); // NOI18N
        pacienteBtn.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Pacientes");
        pacienteBtn.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 130, 66));

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inicioBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
            .addComponent(pacienteBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(inicioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(pacienteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(297, Short.MAX_VALUE))
        );

        background.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 710));

        paineis.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inicioPan.setBackground(new java.awt.Color(196, 231, 219));
        inicioPan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Bem vindo ao Salvation Line");
        inicioPan.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("__________________________________________________________________________");
        inicioPan.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("<html>Obrigado por escolher a nossa aplicação para fazer parte da sua tragetória, explore as as funcionalidades que você possui acesso clicando nas opções do menu ao lado.</html>");
        inicioPan.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 750, 140));

        paineis.add(inicioPan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 710));

        pacPan.setBackground(new java.awt.Color(196, 231, 219));
        pacPan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Pacientes");
        pacPan.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 210, 60));
        pacPan.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 670, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("<html>Visualize a fila de forma ordenada e confirme a vacina dos pacientes já vacinados.<br>Data exibida no formato (ano/mês/dia)</html>");
        pacPan.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 440, 60));

        confirmarVacinaBtn.setText("Confirmar Vacina");
        confirmarVacinaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarVacinaBtnActionPerformed(evt);
            }
        });
        pacPan.add(confirmarVacinaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 630, 210, 50));

        pessoasTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pessoasTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Idade", "Endereco", "UF", "Area saude", "Prioridade", "Data Vacinação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(pessoasTable);

        pacPan.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 900, 480));

        paineis.add(pacPan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 710));

        background.add(paineis, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 930, 710));

        jMenu1.setText("Opções");

        sairMenuItem.setText("Sair");
        sairMenuItem.setToolTipText("Fazer logout");
        sairMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(sairMenuItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inicioBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inicioBtnMouseClicked

        //Botão "inicio", com os métodos (mudarPanel, mudarCor, voltarCor explicados a cima)
        mudarPanel(inicioPan, pacPan);
        mudarCor(inicioBtn);
        voltarCor(pacienteBtn);
    }//GEN-LAST:event_inicioBtnMouseClicked

    private void pacienteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pacienteBtnMouseClicked

        //Botão "paciente", com os métodos (mudarPanel, mudarCor, voltarCor explicados a cima)
        mudarPanel(pacPan, inicioPan);
        mudarCor(pacienteBtn);
        voltarCor(inicioBtn);
        //Obtendo pacientes do banco de dados
        obtemPacientes();
    }//GEN-LAST:event_pacienteBtnMouseClicked

    private void confirmarVacinaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarVacinaBtnActionPerformed
        //Obtendo numero da fileira do paciente selecionado pelo usuário
        int i = pessoasTable.getSelectedRow();
        //Obtendo id da pessoa selecionada passando o numero da fileira
        int codigo = (int) pessoasTable.getValueAt(i, 0);
        //Instanciando data Atual
        Date dataVacina = new Date();
        //Quando confirmado a vacina a prioridade passa a ser 4: Já que o paciente
        //já foi vacinado, por tanto ele vai para o final da fila
        int prioridade = 4;
        //Instaciando objeto p da classe Paciente passando os pârametros:
        //Codigo, dataVacina e prioridade
        Paciente p = new Paciente(codigo, dataVacina, prioridade);
        PacienteDAO pdao = new PacienteDAO();
        
        try {
            //Confirmando vacina do paciente
            pdao.confirmarVacina(p);
            JOptionPane.showMessageDialog(this, "Vacina confirmada com sucesso!");
            
            //Atualizando a fila de pacientes
            obtemPacientes();
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Problemas técnicos, tente novamente mais tarde");
        }
    }//GEN-LAST:event_confirmarVacinaBtnActionPerformed

    private void sairMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairMenuItemActionPerformed
        TelaLogin telalogin = new TelaLogin();
        telalogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_sairMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAdm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton confirmarVacinaBtn;
    private javax.swing.JPanel inicioBtn;
    private javax.swing.JPanel inicioPan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel pacPan;
    private javax.swing.JPanel pacienteBtn;
    private javax.swing.JLayeredPane paineis;
    private javax.swing.JTable pessoasTable;
    private javax.swing.JMenuItem sairMenuItem;
    // End of variables declaration//GEN-END:variables
}
